#!/bin/bash

#Clean up existing files
rm test.ir
rm test.asm

# test.txt is our source.
# Convert to an IR code
python sy.py test.txt

#Convert the RPN-like code to Z80 assembly
python compile.py -TI8X -MAX_PATHS=150 test.ir

#Compile
spasm test.asm bin/test.8xp -I inc -I routines
