#!/bin/bash

#Clean up existing files
rm test.rpn
#rm test.asm

# test.txt is our source.
# Convert to an IR code
python3 sy.py test.txt

#Convert the RPN-like code to Z80 assembly
python3 compile.py -TI8X -MAX_PATHS=150 test.rpn

#Compile
spasm test.asm bin/test.8xp -I inc -I routines
